### PR TITLE
Add dark theme support

### PR DESCRIPTION
**Pull request by darthshittious**
Some users (such as myself) prefer a darker colour scheme. I use this page as my homepage so I look at it a lot.
The current solution is to use a browser extension to inject CSS.
Since this page has a very simple structure, it is trivial to add CSS rules manually.

### CODE REVIEW

**Comment by JohannesNE** [comment]
Beautiful! Could you maybe add a query for direct linking (e.g ?theme=dark)?

**Comment by darthshittious** [comment]
I wouldn't mind doing it, but I don't think this should be enforced via a link. The page automatically switches to dark mode if the [user prefers it](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme). Theme control should only lie with the viewer of the site in my opinion.

**Comment by JohannesNE** [comment]
I think you're right.

**Comment by JohannesNE** [comment]
Also, I did not see that it stores the preference. That's even better.

**Pull request merged**
