### PR TITLE
Clean up code

### PR DESCRIPTION
**Pull request by gbear605**
* Remove Google Analytics
* Make loading json into an async promise
* Declare character set
* Remove unnecessary console log

### CODE REVIEW

**Comment by JohannesNE** [comment]
Thanks. I could not figure out how to make the async loading work.
I'd like to keep analytics, but I'm open to suggestions other than google. I believe people who are concerned about tracking will just block it.

**Comment by gbear605** [comment]
I turned off analytics both because I’m not a fan of it in general, and because I’m running an instance of this project and, no offense, it seems a bit weird to send my data back to you.

Perhaps you could create a patch to add in analytics that you apply when you deploy the code?

**Comment by JohannesNE** [comment]
None taken. I deploy the code from the GitHub pages, but of cause it is appropriate that you remove it from your instance. I really appreciate your pull requests, so please continue. Maybe remove the analytics as a separate commit, making it easier to merge.

**Comment by gbear605** [comment]
Perhaps you could set the repository to deploy the code from a specific branch (I believe this is possible), and then add the commit applying the analytics there. Then you can just merge master into that branch whenever you make changes.

**Pull request merged**
